[env]
TERM = "xterm-256color"

[font]
size = 16

[font.bold]
family = "JetBrainsMono Nerd Font Emoji Uni"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Emoji Uni"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Emoji Uni"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Emoji Uni"
style = "Regular"

[window]
dynamic_padding = false
opacity = 0.89
startup_mode = "Fullscreen"
title = "Alacritty <3"

[window.padding]
x = 0
y = 0
